development: &default
  encoding: utf8
  adapter: postgresql
  min_messages: warning
  timeout: 5000
  url:  <%= "postgres://#{ENV.fetch('AACT_DB_SUPER_USERNAME','ctti')}@localhost:5432/#{ENV.fetch('AACT_ADMIN_DATABASE_NAME','aact_admin')}" %>

test:
  encoding: utf8
  adapter: postgresql
  # database: aact_admin_test
  url:  <%= "postgres://#{ENV.fetch('AACT_DB_SUPER_USERNAME','ctti')}@localhost:5432/aact_admin_test" %>

production: &deploy
  encoding: utf8
  adapter: postgresql
  min_messages: warning
  timeout: 5000
  url:  <%= "postgres://#{ENV.fetch('AACT_DB_SUPER_USERNAME','ctti')}@localhost:5432/#{ENV.fetch('AACT_ADMIN_DATABASE_NAME','aact_admin')}" %>
